import React from "react"
import { styled } from "styled-components"
import { getLibraryIcon } from "./skillsConfig"
import { CSSTransition, TransitionGroup } from "react-transition-group"

export default function JsLibrary({ onClick }) {
  const libraryIcons = getLibraryIcon()

  return (
    <TransitionGroup component={JsLibraryStyled}>
      {libraryIcons.map((icon) => (
        <CSSTransition
          key={icon.id}
          timeout={500}
          classNames={"slide-in-blurred-top"}
          appear={true}
          in={true}
        >
          <div className="container">
            <img
              src={icon.src}
              alt={icon.alt}
              className="icon_library slide-in-blurred-top "
              onClick={onClick}
            />
          </div>
        </CSSTransition>
      ))}
    </TransitionGroup>
  )
}
const JsLibraryStyled = styled.div`
  display: flex;
  height: 48%;
  gap: 25px;
  align-items: center;
  width: 50%;
  .container {
    padding: 20px;
  }
  .slide-in-blurred-top-appear {
    -webkit-transform: translateY(-1000px) scaleY(2.5) scaleX(0.2);
    transform: translateY(-1000px) scaleY(2.5) scaleX(0.2);
    -webkit-transform-origin: 50% 0%;
    transform-origin: 50% 0%;
    -webkit-filter: blur(40px);
    filter: blur(40px);
    opacity: 0;
  }

  .slide-in-blurred-top-appear-active {
    transition: 500ms;
    -webkit-transform: translateY(0) scaleY(1) scaleX(1);
    transform: translateY(0) scaleY(1) scaleX(1);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
    -webkit-filter: blur(0);
    filter: blur(0);
    opacity: 1;
  }

  /* ----------------------------------------------
 * Generated by Animista on 2023-10-14 16:39:4
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation slide-in-blurred-top
 * ----------------------------------------
 */
`
/* ----------------------------------------------
 * Generated by Animista on 2023-10-20 17:16:20
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
/* ----------------------------------------------
 * Generated by Animista on 2023-10-20 17:23:14
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-blurred-top
 * ----------------------------------------
 */
