import React from "react"
import { CSSTransition, TransitionGroup } from "react-transition-group"
import { css, styled } from "styled-components"

export default function TextAnimated({ content, title }) {
  return (
    <TransitionGroup>
      <CSSTransition
        in={true}
        timeout={100}
        appear={true}
        classNames={"tracking-in-contract-bck"}
      >
        <div className="title">
          <h1>{title}</h1>
        </div>
      </CSSTransition>

      <CSSTransition
        in={true}
        timeout={1000}
        appear={true}
        classNames={"span-focus-in"}
      >
        <div>
          <span>{content}</span>
        </div>
      </CSSTransition>
    </TransitionGroup>
  )
}

export const textAnimation = css`
  display: flex;
  flex-direction: column;

  font-size: 16px;
  line-height: 1.9;
  .title {
    width: 100%;
  }
  h1 {
    font-weight: 900;
    font-size: 48px;
    color: #ffba31;
    font-family: "Big Shoulders Stencil Text", " cursive";
  }
  span {
    font-weight: 700;
    overflow: hidden;
  }
  .span-focus-in-appear {
    overflow: hidden;

    -webkit-filter: blur(3px);
    filter: blur(3px);
    opacity: 0;
  }
  .span-focus-in-appear-active {
    overflow: hidden;

    transition: 1000ms;
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
  .tracking-in-contract-bck-appear {
    letter-spacing: 10px;
    -webkit-transform: translateZ(400px);
    transform: translateZ(400px);
    opacity: 0;
  }
  /* .tracking-in-contract-bck-appear-active {
    transition: 300ms;
    opacity: 0;
  } */
  .tracking-in-contract-bck-appear-done {
    transition: 1000ms;

    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
`

/* ----------------------------------------------
 * Generated by Animista on 2023-10-19 17:7:39
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-contract-bck
 * ----------------------------------------
 */
