import React, { useState } from "react"
import { styled } from "styled-components"
import Home from "../sections/home/Home"
import Menu from "../menu/menu-sidebar-right/MenuRight"
import { CSSTransition, TransitionGroup } from "react-transition-group"
import AboutMe from "../sections/about-me/AboutMe"
import Resume from "../sections/resume/Resume"
import FirstPageContext from "./FirstPageContext"

export default function FirstPage() {
  const [section, setSection] = useState("")
  const FirstPageValue = { section, setSection }
  return (
    <FirstPageStyled>
      <FirstPageContext.Provider value={FirstPageValue}>
        {section === "" && <Home />}
        <Menu />
        {section === "aboutme" && (
          <CSSTransition
            appear={true}
            classNames={"puff-in-center"}
            timeout={700}
            in={true}
          >
            <AboutMe />
          </CSSTransition>
        )}
        {/* <Resume /> */}
      </FirstPageContext.Provider>
    </FirstPageStyled>
  )
}

const FirstPageStyled = styled.div`
  position: relative;
  width: 100%;
  height: 100vh;
  padding: 80px;

  &::before {
    content: "";
    background: url("src/assets/pawel-nolbert-4u2U8EO9OzY-unsplash.jpg")
      rgba(0, 0, 0, 0.7);
    background-size: cover;
    background-position: center;
    background-blend-mode: darken;
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: -1;
  }

  .puff-in-center-appear {
    transform: translateY(100%);
  }

  .puff-in-center-appear-active {
    transform: translateY(0%);
    transition: 0.7s;
  }

  .puff-in-center {
    -webkit-animation: puff-in-center 0.7s cubic-bezier(0.47, 0, 0.745, 0.715)
      both;
    animation: puff-in-center 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) both;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2023-10-20 16:18:43
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation puff-in-center
 * ----------------------------------------
 */

  /* .scale-in-center-enter-active {
    transition: 1000ms;
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
  .scale-in-center-enter-done {
    transition: 1000ms;
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  } */

  /* .puff-in-center {
    -webkit-animation: puff-in-center 0.7s cubic-bezier(0.47, 0, 0.745, 0.715)
      both;
    animation: puff-in-center 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) both;
  } */
  /* ----------------------------------------------
 * Generated by Animista on 2023-10-20 11:47:51
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation puff-in-center
 * ----------------------------------------
 */
  /* @-webkit-keyframes puff-in-center {
    0% {
      -webkit-transform: scale(2);
      transform: scale(2);
      -webkit-filter: blur(4px);
      filter: blur(4px);
      opacity: 0;
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
      -webkit-filter: blur(0px);
      filter: blur(0px);
      opacity: 1;
    }
  }
  @keyframes puff-in-center {
    0% {
      -webkit-transform: scale(2);
      transform: scale(2);
      -webkit-filter: blur(4px);
      filter: blur(4px);
      opacity: 0;
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
      -webkit-filter: blur(0px);
      filter: blur(0px);
      opacity: 1;
    }
  } */
`
